FORMAT: 1A
HOST: http://ibis.ibisoft.cz/

# Ibis

API pro práci s pacientem

## Ping [/ping]

### Ověření dostupnosti API  [GET]

+ Response 200 (application/json)

        {
            "status": "OK"
        }

## Pacienti [/pacient/{pacient_id}]

### Načtení pacienta [GET]

Vrací detail konkrétního pacienta.

Tato akce vrací kód 200 a JSON objekt reprezentující pacienta.

+ Parameters
    + pacient_id (guid) - ID pacienta
    
+ Response 200 (application/json)
    
    + Schema
    
            {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "description": "Nacteni pacienta",
                "type": "object",
                "properties": {
                    "CP": {
                        "type": "string",
                        "description": "Cislo pojistence",
                        "pattern": "^[0-9]{9,10}$"
                    }
                }
            }
            
    + Body
            
            {
                "CP": "85030955664"
            }