FORMAT: 1A
HOST: https://my-ibis.herokuapp.com

# Ibis

API pro práci s pacientem.

## Ping [/ping]

### Ověření dostupnosti API  [GET]

+ Response 200 (application/json)

        {
            "status": "OK"
        }

## Pacienti [/patient/{pacient_id}]

### Načtení pacienta [GET]

Vrací detail konkrétního pacienta.

Tato akce vrací kód 200 a JSON objekt reprezentující pacienta.

+ Parameters
    + pacient_id (required, guid) - ID pacienta
    
+ Response 200 (application/json;charset=UTF-8)

    + Attributes (Pacient)
            
    
# Data Structures

## Pacient (object)
+ insuranceNumber: 1122334455 (required, string)
+ adresa (Adresa)

## Adresa (object)
+ ulice: Pernerova (required)
+ cisloPopisne: 444 (required, string)