/*  -------------------------------------------------- */
/*  Generated by Enterprise Architect Version 11.1.1110*/
/*  Created On : støeda, 29 èerven, 2016 */
/*  DBMS       : PostgreSQL */
/*  -------------------------------------------------- */

SET SCHEMA 'iBIS200';


/* Drop Tables, Stored Procedures and Views */

DROP TABLE KARTA CASCADE;
DROP TABLE LEKARI CASCADE;
DROP TABLE LEKARNICI CASCADE;
DROP TABLE NASTAVENI CASCADE;
DROP TABLE OTP_KOD CASCADE;
DROP TABLE PACIENT CASCADE;
DROP TABLE PREDPIS CASCADE;
DROP TABLE PRISTUPOVY_KOD CASCADE;
DROP TABLE VYROBCI_SW CASCADE;
DROP TABLE ZASTUP CASCADE;
DROP TABLE ZPRAVA CASCADE;

/* Create Tables */
CREATE TABLE KARTA ( 
	ID uuid DEFAULT gen_random_uuid() NOT NULL,
	ID_PACIENTA uuid,    /* ID pacienta, ke kterému se kód váže. */
	VERZE_ZAZNAMU numeric(9) DEFAULT 1,
	DATUMCASZALOZENI timestamp(1) with time zone DEFAULT current_timestamp NOT NULL,    /* Datum a èas založení úètu */
	DATUMCASZMENY timestamp(1) with time zone DEFAULT current_timestamp NOT NULL,    /* Datum a èas zmìny pacienta */
	STAVKARTY varchar(20) DEFAULT 'AKTIVNI',    /* Stav karty AKTIVNI  ZABLOKOVANA */
	TYPKARTY varchar(20),    /* Typ karty - vydavatel Napø.: Dr.Max, Benu,... */
	KODKARTY varchar(25)    /* Identifikaèní kód karty */
);
COMMENT ON TABLE KARTA
    IS 'Karta lékarny, kterou se pacient identifikuje pøi výdeji LP na recepty.';
COMMENT ON COLUMN KARTA.ID_PACIENTA
    IS 'ID pacienta, ke kterému se kód váže.';
COMMENT ON COLUMN KARTA.DATUMCASZALOZENI
    IS 'Datum a èas založení úètu';
COMMENT ON COLUMN KARTA.DATUMCASZMENY
    IS 'Datum a èas zmìny pacienta';
COMMENT ON COLUMN KARTA.STAVKARTY
    IS 'Stav karty AKTIVNI  ZABLOKOVANA';
COMMENT ON COLUMN KARTA.TYPKARTY
    IS 'Typ karty - vydavatel Napø.: Dr.Max, Benu,...';
COMMENT ON COLUMN KARTA.KODKARTY
    IS 'Identifikaèní kód karty';

CREATE TABLE LEKARI ( 
	ID uuid DEFAULT gen_random_uuid() NOT NULL,
	VERZE_ZAZNAMU numeric(9) DEFAULT 1,
	DATUMCASZALOZENI timestamp(1) with time zone DEFAULT current_timestamp NOT NULL,    /* Datum a èas založení úètu */
	DATUMCASZMENY timestamp(1) with time zone DEFAULT current_timestamp NOT NULL,    /* Datum a èas zmìny pacienta */
	ID_VYROBCE_SW uuid,    /* ID výrobce SW pøes který uživatel pøistupuje. */
	STAVUCTU varchar(50) DEFAULT 'AKTIVNI',    /* Informace o stavu úètu lékaøe -  AKTUVNI, ZABLOKOVANY */
	JMENA varchar(24),    /* Jména osoby, která pøedepsala - lékaøe nebo lékárník, který vystavil výpis */
	PRIJMENI varchar(35),    /* Pøíjmení osoby, která pøedepsala - lékaøe nebo lékárník, který vystavil výpis */
	NAZEV_POSKYTOVATELE varchar(200),    /* Název poskytovatele zdrav. služeb osoby, která pøedepsala - lékaøe nebo lékárník, který vystavil výpis */
	ADRESA_POSKYTOVATELE varchar(200),    /* Adresa poskytovatele osoby, která pøedepsala - lékaøe nebo lékárník, který vystavil výpis */
	ICZ_POSKYTOVATELE varchar(8),    /* IÈZ poskytovatele osoby, která pøedepsala - lékaøe nebo lékárník, který vystavil výpis Jednoznaèný idenfifikaèní kód zdravotnického zaøízení pøidìlený VZP. */
	ID_OSOBY_LEKARE varchar(36),    /* GUID osoby poskytovatele, která pøedepsala - lékaøe nebo lékárník, který vystavil výpis */
	KOD_PRACOVISTE_PREDEPISUJICI varchar(20),    /* Kód pracivištì pøedepisující LP */
	EMAIL varchar(50),    /* Emailový kontakt na lékárníka/lékárnu */
	TELEFON varchar(50)    /* Telefonní kontakt na lékárnu. */
);
COMMENT ON TABLE LEKARI
    IS 'Evidience pøístupù lékaøù - oznámení pøístup a stav "úètu" lékaøe. ';
COMMENT ON COLUMN LEKARI.DATUMCASZALOZENI
    IS 'Datum a èas založení úètu';
COMMENT ON COLUMN LEKARI.DATUMCASZMENY
    IS 'Datum a èas zmìny pacienta';
COMMENT ON COLUMN LEKARI.ID_VYROBCE_SW
    IS 'ID výrobce SW pøes který uživatel pøistupuje.';
COMMENT ON COLUMN LEKARI.STAVUCTU
    IS 'Informace o stavu úètu lékaøe -  AKTUVNI, ZABLOKOVANY';
COMMENT ON COLUMN LEKARI.JMENA
    IS 'Jména osoby, která pøedepsala - lékaøe nebo lékárník, který vystavil výpis';
COMMENT ON COLUMN LEKARI.PRIJMENI
    IS 'Pøíjmení osoby, která pøedepsala - lékaøe nebo lékárník, který vystavil výpis';
COMMENT ON COLUMN LEKARI.NAZEV_POSKYTOVATELE
    IS 'Název poskytovatele zdrav. služeb osoby, která pøedepsala - lékaøe nebo lékárník, který vystavil výpis';
COMMENT ON COLUMN LEKARI.ADRESA_POSKYTOVATELE
    IS 'Adresa poskytovatele osoby, která pøedepsala - lékaøe nebo lékárník, který vystavil výpis';
COMMENT ON COLUMN LEKARI.ICZ_POSKYTOVATELE
    IS 'IÈZ poskytovatele osoby, která pøedepsala - lékaøe nebo lékárník, který vystavil výpis Jednoznaèný idenfifikaèní kód zdravotnického zaøízení pøidìlený VZP.';
COMMENT ON COLUMN LEKARI.ID_OSOBY_LEKARE
    IS 'GUID osoby poskytovatele, která pøedepsala - lékaøe nebo lékárník, který vystavil výpis';
COMMENT ON COLUMN LEKARI.KOD_PRACOVISTE_PREDEPISUJICI
    IS 'Kód pracivištì pøedepisující LP';
COMMENT ON COLUMN LEKARI.EMAIL
    IS 'Emailový kontakt na lékárníka/lékárnu';
COMMENT ON COLUMN LEKARI.TELEFON
    IS 'Telefonní kontakt na lékárnu.';

CREATE TABLE LEKARNICI ( 
	ID uuid DEFAULT gen_random_uuid() NOT NULL,
	VERZE_ZAZNAMU numeric(9) DEFAULT 1,
	DATUMCASZALOZENI timestamp(1) with time zone DEFAULT current_timestamp NOT NULL,    /* Datum a èas založení úètu */
	DATUMCASZMENY timestamp(1) with time zone DEFAULT current_timestamp NOT NULL,    /* Datum a èas zmìny pacienta */
	ID_VYROBCE_SW uuid,    /* ID výrobce SW pøes který uživatel pøistupuje. */
	STAVUCTU varchar(50) DEFAULT 'AKTIVNI',    /* Informace o stavu úètu lékaøe -  AKTUVNI, ZABLOKOVANY */
	JMENA varchar(24),    /* Jména osoby, která vydala - lékárník */
	PRIJMENI varchar(35),    /* Pøíjmení osoby, která vydala - lékárník */
	NAZEV_POSKYTOVATELE varchar(200),    /* Název poskytovatele zdrav. služeb osoby, která vydala- lékárník Dr.Max LÉKÁRNA */
	ADRESA_POSKYTOVATELE varchar(200),    /* Adresa poskytovatele osoby, která vydala- lékárník - Bìlehradská 660, 533 51 Pardubice, Pardubice */
	ICZ_POSKYTOVATELE varchar(8),    /* IÈZ poskytovatele osoby, která vydala-lékárník Jednoznaèný idenfifikaèní kód zdravotnického zaøízení pøidìlený VZP. */
	ID_OSOBY_LEKARNIKA varchar(36),    /* GUID osoby poskytovatele, která vydala - lékárník */
	KOD_PRACOVISTE varchar(20),    /* Kód pracovištì vydávající LP 65449000000 - odkaz na http://www.sukl.cz/lekarna/65449000000 */
	EMAIL varchar(50),    /* Emailový kontakt na lékárníka/lékárnu */
	TELEFON varchar(50)    /* Telefonní kontakt na lékárnu. */
);
COMMENT ON TABLE LEKARNICI
    IS 'Evidience pøístupù lékárníkù - oznámení pøístup a stav "úètu" lékárníka. ';
COMMENT ON COLUMN LEKARNICI.DATUMCASZALOZENI
    IS 'Datum a èas založení úètu';
COMMENT ON COLUMN LEKARNICI.DATUMCASZMENY
    IS 'Datum a èas zmìny pacienta';
COMMENT ON COLUMN LEKARNICI.ID_VYROBCE_SW
    IS 'ID výrobce SW pøes který uživatel pøistupuje.';
COMMENT ON COLUMN LEKARNICI.STAVUCTU
    IS 'Informace o stavu úètu lékaøe -  AKTUVNI, ZABLOKOVANY';
COMMENT ON COLUMN LEKARNICI.JMENA
    IS 'Jména osoby, která vydala - lékárník';
COMMENT ON COLUMN LEKARNICI.PRIJMENI
    IS 'Pøíjmení osoby, která vydala - lékárník';
COMMENT ON COLUMN LEKARNICI.NAZEV_POSKYTOVATELE
    IS 'Název poskytovatele zdrav. služeb osoby, která vydala- lékárník Dr.Max LÉKÁRNA';
COMMENT ON COLUMN LEKARNICI.ADRESA_POSKYTOVATELE
    IS 'Adresa poskytovatele osoby, která vydala- lékárník - Bìlehradská 660, 533 51 Pardubice, Pardubice';
COMMENT ON COLUMN LEKARNICI.ICZ_POSKYTOVATELE
    IS 'IÈZ poskytovatele osoby, která vydala-lékárník Jednoznaèný idenfifikaèní kód zdravotnického zaøízení pøidìlený VZP.';
COMMENT ON COLUMN LEKARNICI.ID_OSOBY_LEKARNIKA
    IS 'GUID osoby poskytovatele, která vydala - lékárník';
COMMENT ON COLUMN LEKARNICI.KOD_PRACOVISTE
    IS 'Kód pracovištì vydávající LP 65449000000 - odkaz na http://www.sukl.cz/lekarna/65449000000';
COMMENT ON COLUMN LEKARNICI.EMAIL
    IS 'Emailový kontakt na lékárníka/lékárnu';
COMMENT ON COLUMN LEKARNICI.TELEFON
    IS 'Telefonní kontakt na lékárnu.';

CREATE TABLE NASTAVENI ( 
	ID uuid DEFAULT gen_random_uuid() NOT NULL,
	DATUMCASZALOZENI timestamp(1) with time zone DEFAULT current_timestamp NOT NULL,    /* Datum a èas založení úètu */
	DATUMCASZMENY timestamp(1) with time zone DEFAULT current_timestamp NOT NULL,    /* Datum a èas zmìny pacienta */
	VERZE_ZAZNAMU numeric(9) DEFAULT 1,
	ID_PACIENTA uuid,    /* ID pacienta, ke kterému se kód váže. */
	PREFEROVANA_KOMUNIKACE varchar(50) DEFAULT 'MOBILNI_APLIKACE',    /* Preferovaný zpùsob komunikace s pacientem SMS MOBILNI_APLIKACE MOBILNI_APLIKACE_SMS */
	DOBA_UCHOVANI numeric(6) DEFAULT 2000,    /* Doba uchovávání identifikátorù v úložišti ve dnech. */
	PRISTUP_NA_IDENTIFIKATORY varchar(50) DEFAULT 'PREDEPSANE_VYDANE',    /* Informace o pøístupu na identifikátory: všechny  - pøedepsané i vydané, nevydané - pouze nevydané, novì pøedepsané        */
	ZPUSOB_PRISTUPU varchar(50) DEFAULT 'OTP_KOD'    /* Zpùsob komunikace s úložištìm - pøístup na identifikátory eReceptù: prostøednictvím bonusových karet nebo karet pojištìnce, prostøednictvím generovaných jednorázových OTP kódù           */
);
COMMENT ON TABLE NASTAVENI
    IS 'Nastavenií úètu pacienta.';
COMMENT ON COLUMN NASTAVENI.DATUMCASZALOZENI
    IS 'Datum a èas založení úètu';
COMMENT ON COLUMN NASTAVENI.DATUMCASZMENY
    IS 'Datum a èas zmìny pacienta';
COMMENT ON COLUMN NASTAVENI.ID_PACIENTA
    IS 'ID pacienta, ke kterému se kód váže.';
COMMENT ON COLUMN NASTAVENI.PREFEROVANA_KOMUNIKACE
    IS 'Preferovaný zpùsob komunikace s pacientem SMS MOBILNI_APLIKACE MOBILNI_APLIKACE_SMS';
COMMENT ON COLUMN NASTAVENI.DOBA_UCHOVANI
    IS 'Doba uchovávání identifikátorù v úložišti ve dnech.';
COMMENT ON COLUMN NASTAVENI.PRISTUP_NA_IDENTIFIKATORY
    IS 'Informace o pøístupu na identifikátory: všechny  - pøedepsané i vydané, nevydané - pouze nevydané, novì pøedepsané       ';
COMMENT ON COLUMN NASTAVENI.ZPUSOB_PRISTUPU
    IS 'Zpùsob komunikace s úložištìm - pøístup na identifikátory eReceptù: prostøednictvím bonusových karet nebo karet pojištìnce, prostøednictvím generovaných jednorázových OTP kódù          ';

CREATE TABLE OTP_KOD ( 
	ID uuid DEFAULT gen_random_uuid() NOT NULL,
	OTP_KOD varchar(10),    /* Kód ve formátu: XXXX-XXXX */
	DATUMCASZALOZENI timestamp(1) with time zone DEFAULT current_timestamp NOT NULL,    /* Datum a èas založení úètu */
	DATUMCASZMENY timestamp(1) with time zone DEFAULT current_timestamp NOT NULL,    /* Datum a èas zmìny pacienta */
	VERZE_ZAZNAMU numeric(9) DEFAULT 1
);
COMMENT ON TABLE OTP_KOD
    IS 'Evidence jednorázových OTP kódù pro pøístup k identifikátorùm receptù, OTP kódù pro zastupování a pro jednorázové pøihlášení. 
 Data bude mazat DB JOB napø. po pìti letech, aby nebylo možné znovu vygenerovat ten samý kód behem tohoto èasového intervalu. 
 Každý OPT kód musí být uložen v této tabulce pro kontrolu unikátnosti v rámci celého systému.';
COMMENT ON COLUMN OTP_KOD.OTP_KOD
    IS 'Kód ve formátu: XXXX-XXXX';
COMMENT ON COLUMN OTP_KOD.DATUMCASZALOZENI
    IS 'Datum a èas založení úètu';
COMMENT ON COLUMN OTP_KOD.DATUMCASZMENY
    IS 'Datum a èas zmìny pacienta';

CREATE TABLE PACIENT ( 
	ID uuid DEFAULT gen_random_uuid() NOT NULL,
	DATUMCASZALOZENI timestamp(1) with time zone DEFAULT current_timestamp NOT NULL,    /* Datum a èas založení úètu */
	DATUMCASZMENY timestamp(1) with time zone DEFAULT current_timestamp NOT NULL,    /* Datum a èas zmìny pacienta */
	VERZE_ZAZNAMU numeric(9) DEFAULT 1,
	CP varchar(10) NOT NULL,    /* Èíslo pojištìnce */
	H_HESLO varchar(65) NOT NULL,    /* Hash SHA-256 hesla */
	PRIJMENI varchar(35) NOT NULL,    /* Pøíjmení fyzické osoby */
	JMENA varchar(24) NOT NULL,    /* Jména fyzické osoby */
	EMAIL varchar(50),    /* eMailový úèet */
	MOBIL varchar(20),    /* Èíslo mobilního telefonu pro zasílání SMS. */
	STAVUCTU varchar(50) DEFAULT 'AKTIVNI',    /* Informace o stavu úètu pacienta. */
	OTP_KOD_PROZASTUPOVANI uuid,
	OTP_KOD_PROPRIHLASENI uuid
);
COMMENT ON TABLE PACIENT
    IS 'Pacient a inforamce o nìm - majitel úètu';
COMMENT ON COLUMN PACIENT.DATUMCASZALOZENI
    IS 'Datum a èas založení úètu';
COMMENT ON COLUMN PACIENT.DATUMCASZMENY
    IS 'Datum a èas zmìny pacienta';
COMMENT ON COLUMN PACIENT.CP
    IS 'Èíslo pojištìnce';
COMMENT ON COLUMN PACIENT.H_HESLO
    IS 'Hash SHA-256 hesla';
COMMENT ON COLUMN PACIENT.PRIJMENI
    IS 'Pøíjmení fyzické osoby';
COMMENT ON COLUMN PACIENT.JMENA
    IS 'Jména fyzické osoby';
COMMENT ON COLUMN PACIENT.EMAIL
    IS 'eMailový úèet';
COMMENT ON COLUMN PACIENT.MOBIL
    IS 'Èíslo mobilního telefonu pro zasílání SMS.';
COMMENT ON COLUMN PACIENT.STAVUCTU
    IS 'Informace o stavu úètu pacienta.';

CREATE TABLE PREDPIS ( 
	ID uuid DEFAULT gen_random_uuid() NOT NULL,
	ID_PACIENTA uuid,    /* ID pacienta, ke kterému se kód váže. */
	VERZE_ZAZNAMU numeric(9) DEFAULT 1,
	DATUMCASZALOZENI timestamp(1) with time zone DEFAULT current_timestamp NOT NULL,    /* Datum a èas založení úètu */
	DATUMCASZMENY timestamp(1) with time zone DEFAULT current_timestamp NOT NULL,    /* Datum a èas zmìny pacienta */
	ID_DOKLADU_ERP varchar(36) NOT NULL,    /* Identifikátor púøedpisu. */
	PLATNOST timestamp with time zone,    /* Platnost pøedpisu DO */
	STAV varchar(8),    /* Stav identifikátoru - NOVÝ - VYØÍZENÝ */
	KOD_SUKL_LP1 varchar(10),    /* Kód SÚKL LP1 - pro lékaøe/lékárnu 0091249 - odlaz na info o LP http://www.sukl.cz/modules/medication/detail.php?kod=0091249 */
	KOD_SUKL_LP2 varchar(10),    /* Kód SÚKL LP1 - pro lékaøe/lékárnu 0201974 - odlaz na info o LP http://www.sukl.cz/modules/medication/detail.php?kod=0201974 */
	NAZEV_LP1 varchar(100),    /* Textová informace o pøedepsaném LP1 pro pacienta: PENICILIN G 1,0 INJ PLV SOL 10X1MU */
	NAZEV_LP2 varchar(100),    /* Textová informace o pøedepsaném LP2 pro pacienta: PARALEN 100 RCT SUP 5X100MG */
	MNOZSTVI_LP1 numeric(9,3),    /* Množství LP 1 */
	MNOZSTVI_LP2 numeric(9,3),    /* Množství LP 2 */
	ID_PREDEPISUJICIHO_LEKARE uuid,    /* ID pøedepisujícího lékaøe - pøedepsané recepty. */
	ID_PREDEPISUJICIHO_LEKARNIKA uuid,    /* ID pøedepisujícího lékárníka - výpisy z receptù. */
	ID_VYDAVAJICIHO_LEKARNIKA uuid    /* ID vydávajícéího lékárníka - výdej receptù. */
);
COMMENT ON TABLE PREDPIS
    IS 'Pøedpis nebo výpis z pøedpisu, opakovací recept. 
 odkaz na: http://www.vzpsmlouvy.cz/rubrika/ic-icz/icz/65084000';
COMMENT ON COLUMN PREDPIS.ID_PACIENTA
    IS 'ID pacienta, ke kterému se kód váže.';
COMMENT ON COLUMN PREDPIS.DATUMCASZALOZENI
    IS 'Datum a èas založení úètu';
COMMENT ON COLUMN PREDPIS.DATUMCASZMENY
    IS 'Datum a èas zmìny pacienta';
COMMENT ON COLUMN PREDPIS.ID_DOKLADU_ERP
    IS 'Identifikátor púøedpisu.';
COMMENT ON COLUMN PREDPIS.PLATNOST
    IS 'Platnost pøedpisu DO';
COMMENT ON COLUMN PREDPIS.STAV
    IS 'Stav identifikátoru - NOVÝ - VYØÍZENÝ';
COMMENT ON COLUMN PREDPIS.KOD_SUKL_LP1
    IS 'Kód SÚKL LP1 - pro lékaøe/lékárnu 0091249 - odlaz na info o LP http://www.sukl.cz/modules/medication/detail.php?kod=0091249';
COMMENT ON COLUMN PREDPIS.KOD_SUKL_LP2
    IS 'Kód SÚKL LP1 - pro lékaøe/lékárnu 0201974 - odlaz na info o LP http://www.sukl.cz/modules/medication/detail.php?kod=0201974';
COMMENT ON COLUMN PREDPIS.NAZEV_LP1
    IS 'Textová informace o pøedepsaném LP1 pro pacienta: PENICILIN G 1,0 INJ PLV SOL 10X1MU';
COMMENT ON COLUMN PREDPIS.NAZEV_LP2
    IS 'Textová informace o pøedepsaném LP2 pro pacienta: PARALEN 100 RCT SUP 5X100MG';
COMMENT ON COLUMN PREDPIS.MNOZSTVI_LP1
    IS 'Množství LP 1';
COMMENT ON COLUMN PREDPIS.MNOZSTVI_LP2
    IS 'Množství LP 2';
COMMENT ON COLUMN PREDPIS.ID_PREDEPISUJICIHO_LEKARE
    IS 'ID pøedepisujícího lékaøe - pøedepsané recepty.';
COMMENT ON COLUMN PREDPIS.ID_PREDEPISUJICIHO_LEKARNIKA
    IS 'ID pøedepisujícího lékárníka - výpisy z receptù.';
COMMENT ON COLUMN PREDPIS.ID_VYDAVAJICIHO_LEKARNIKA
    IS 'ID vydávajícéího lékárníka - výdej receptù.';

CREATE TABLE PRISTUPOVY_KOD ( 
	ID uuid DEFAULT gen_random_uuid() NOT NULL,
	ID_PACIENTA uuid,    /* ID pacienta, ke kterému se kód váže. */
	OTP_KOD uuid,
	PLATNOST_DO timestamp with time zone,    /* Platnost kódu do data a èasu od prvního použití. Umožní opakovanì kód použít po zadaný èasový interval (minuty). */
	DATUMCASZALOZENI timestamp(1) with time zone DEFAULT current_timestamp NOT NULL,    /* Datum a èas založení úètu */
	DATUMCASZMENY timestamp(1) with time zone DEFAULT current_timestamp NOT NULL,    /* Datum a èas zmìny pacienta */
	VERZE_ZAZNAMU numeric(9) DEFAULT 1,
	ID_PREDEPISUJICIHO_LEKARE uuid,    /* ID pøedepisujícího lékaøe - pøedepsané recepty. */
	ID_VYDAVAJICIHO_LEKARNIKA uuid    /* ID vydávajícéího lékárníka - výdej receptù. */
);
COMMENT ON TABLE PRISTUPOVY_KOD
    IS 'Identifikace osoby, která použila OTP kód';
COMMENT ON COLUMN PRISTUPOVY_KOD.ID_PACIENTA
    IS 'ID pacienta, ke kterému se kód váže.';
COMMENT ON COLUMN PRISTUPOVY_KOD.PLATNOST_DO
    IS 'Platnost kódu do data a èasu od prvního použití. Umožní opakovanì kód použít po zadaný èasový interval (minuty).';
COMMENT ON COLUMN PRISTUPOVY_KOD.DATUMCASZALOZENI
    IS 'Datum a èas založení úètu';
COMMENT ON COLUMN PRISTUPOVY_KOD.DATUMCASZMENY
    IS 'Datum a èas zmìny pacienta';
COMMENT ON COLUMN PRISTUPOVY_KOD.ID_PREDEPISUJICIHO_LEKARE
    IS 'ID pøedepisujícího lékaøe - pøedepsané recepty.';
COMMENT ON COLUMN PRISTUPOVY_KOD.ID_VYDAVAJICIHO_LEKARNIKA
    IS 'ID vydávajícéího lékárníka - výdej receptù.';

CREATE TABLE VYROBCI_SW ( 
	ID uuid DEFAULT gen_random_uuid() NOT NULL,
	VERZE_ZAZNAMU numeric(9) DEFAULT 1,
	DATUMCASZALOZENI timestamp(1) with time zone DEFAULT current_timestamp NOT NULL,    /* Datum a èas založení úètu */
	DATUMCASZMENY timestamp(1) with time zone DEFAULT current_timestamp NOT NULL,    /* Datum a èas zmìny pacienta */
	NAZEV_VYROBCE_SW varchar(100),
	NAZEV_SW varchar(200),    /* Název SW výrobce */
	KLIC_VYROBCE varchar(36)    /* Klíè pro pøístup z SW výrobce do úložištì. */
);
COMMENT ON TABLE VYROBCI_SW
    IS 'Tabulka pro evidenci výrobcù SW a jejich tajemství, prostøednictvím kterých jejich uživatelé oznamují pøístup.';
COMMENT ON COLUMN VYROBCI_SW.DATUMCASZALOZENI
    IS 'Datum a èas založení úètu';
COMMENT ON COLUMN VYROBCI_SW.DATUMCASZMENY
    IS 'Datum a èas zmìny pacienta';
COMMENT ON COLUMN VYROBCI_SW.NAZEV_SW
    IS 'Název SW výrobce';
COMMENT ON COLUMN VYROBCI_SW.KLIC_VYROBCE
    IS 'Klíè pro pøístup z SW výrobce do úložištì.';

CREATE TABLE ZASTUP ( 
	ID uuid DEFAULT gen_random_uuid() NOT NULL,
	ZASTUPOVANY_ID uuid NOT NULL,    /* ID zastupovaného */
	ZASTUPUJICI_ID uuid NOT NULL,    /* ID Zastupujícího */
	VERZE_ZAZNAMU numeric(9) DEFAULT 1,
	DATUMCASZALOZENI timestamp(1) with time zone DEFAULT current_timestamp NOT NULL,    /* Datum a èas založení úètu */
	DATUMCASZMENY timestamp(1) with time zone DEFAULT current_timestamp NOT NULL    /* Datum a èas zmìny zástupu */
);
COMMENT ON TABLE ZASTUP
    IS 'Zastupování osoby pacienta';
COMMENT ON COLUMN ZASTUP.ZASTUPOVANY_ID
    IS 'ID zastupovaného';
COMMENT ON COLUMN ZASTUP.ZASTUPUJICI_ID
    IS 'ID Zastupujícího';
COMMENT ON COLUMN ZASTUP.DATUMCASZALOZENI
    IS 'Datum a èas založení úètu';
COMMENT ON COLUMN ZASTUP.DATUMCASZMENY
    IS 'Datum a èas zmìny zástupu';

CREATE TABLE ZPRAVA ( 
	ID uuid DEFAULT gen_random_uuid() NOT NULL,
	ID_PACIENTA uuid,    /* ID pacienta, ke kterému se identifikátor váže. */
	VERZE_ZAZNAMU numeric(9) DEFAULT 1,
	DATUMCASZALOZENI timestamp(1) with time zone DEFAULT current_timestamp NOT NULL,    /* Datum a èas založení úètu */
	DATUMCASZMENY timestamp(1) with time zone DEFAULT current_timestamp NOT NULL,    /* Datum a èas zmìny pacienta */
	MOBIL varchar(20),    /* Èíslo mobilního telefonu, na který byla SMS zpráva odeslána. */
	EMAIL varchar(50),    /* eMail, na který byla zpráva odeslána. */
	ODESLANY_TEXT varchar(2048),    /* Odeslaný text zprávy. */
	DATUMCASODESLANI timestamp with time zone,    /* Datum a èas odeslání zprávy. */
	ID_PREDEPISUJICIHO_LEKARE uuid,    /* ID pøedepisujícího lékaøe - pøedepsané recepty. */
	ID_VYDAVAJICIHO_LEKARNIKA uuid    /* ID vydávajícéího lékárníka - výdej receptù. */
);
COMMENT ON TABLE ZPRAVA
    IS 'Evidence odeslaných SMS a eMail zpráv. Historie komunikace pro pacienta.';
COMMENT ON COLUMN ZPRAVA.ID_PACIENTA
    IS 'ID pacienta, ke kterému se identifikátor váže.';
COMMENT ON COLUMN ZPRAVA.DATUMCASZALOZENI
    IS 'Datum a èas založení úètu';
COMMENT ON COLUMN ZPRAVA.DATUMCASZMENY
    IS 'Datum a èas zmìny pacienta';
COMMENT ON COLUMN ZPRAVA.MOBIL
    IS 'Èíslo mobilního telefonu, na který byla SMS zpráva odeslána.';
COMMENT ON COLUMN ZPRAVA.EMAIL
    IS 'eMail, na který byla zpráva odeslána.';
COMMENT ON COLUMN ZPRAVA.ODESLANY_TEXT
    IS 'Odeslaný text zprávy.';
COMMENT ON COLUMN ZPRAVA.DATUMCASODESLANI
    IS 'Datum a èas odeslání zprávy.';
COMMENT ON COLUMN ZPRAVA.ID_PREDEPISUJICIHO_LEKARE
    IS 'ID pøedepisujícího lékaøe - pøedepsané recepty.';
COMMENT ON COLUMN ZPRAVA.ID_VYDAVAJICIHO_LEKARNIKA
    IS 'ID vydávajícéího lékárníka - výdej receptù.';


/* Create Indexes */
CREATE INDEX IXFK_KARTA_PACIENT
	ON KARTA (ID_PACIENTA);
ALTER TABLE KARTA
	ADD CONSTRAINT UQ_KARTA UNIQUE (TYPKARTY, KODKARTY);
CREATE INDEX IXFK_LEKARI_VYROBCI_SW
	ON LEKARI (ID_VYROBCE_SW);
CREATE INDEX IXFK_LEKARNICI_VYROBCI_SW
	ON LEKARNICI (ID_VYROBCE_SW);
CREATE INDEX IXFK_NASTAVENI_PACIENT
	ON NASTAVENI (ID_PACIENTA);
ALTER TABLE OTP_KOD
	ADD CONSTRAINT UQ_OTP_KOD_OTP_KOD UNIQUE (OTP_KOD);
CREATE UNIQUE INDEX IDX_PACIENT_CP
	ON PACIENT (CP);
CREATE INDEX IXFK_PACIENT_OTP_KOD
	ON PACIENT (OTP_KOD_PROZASTUPOVANI);
CREATE INDEX IXFK_PACIENT_OTP_KOD_02
	ON PACIENT (OTP_KOD_PROPRIHLASENI);
ALTER TABLE PACIENT
	ADD CONSTRAINT CHECK_OTP_KODY CHECK (OTP_KOD_PROZASTUPOVANI <> null AND OTP_KOD_PROZASTUPOVANI <> OTP_KOD_PROPRIHLASENI);
ALTER TABLE PACIENT
	ADD CONSTRAINT UQ_OTP_ZASTUPOVANI UNIQUE (OTP_KOD_PROZASTUPOVANI);
ALTER TABLE PACIENT
	ADD CONSTRAINT UQ_OTP_PRIHLASENI UNIQUE (OTP_KOD_PROPRIHLASENI);
ALTER TABLE PACIENT
	ADD CONSTRAINT UQ_OTP_ZAST_PRIH UNIQUE (OTP_KOD_PROZASTUPOVANI, OTP_KOD_PROPRIHLASENI);
CREATE INDEX IXFK_PREDPIS_PACIENT
	ON PREDPIS (ID_PACIENTA);
ALTER TABLE PREDPIS
	ADD CONSTRAINT UQ_PREDPIS_ID_DOKLADU_ERP UNIQUE (ID_DOKLADU_ERP);
CREATE INDEX IXFK_PREDPIS_LEKARNICI
	ON PREDPIS (ID_PREDEPISUJICIHO_LEKARNIKA);
CREATE INDEX IXFK_PREDPIS_LEKARNICI_02
	ON PREDPIS (ID_VYDAVAJICIHO_LEKARNIKA);
CREATE INDEX IXFK_PREDPIS_LEKARI
	ON PREDPIS (ID_PREDEPISUJICIHO_LEKARE);
CREATE INDEX IXFK_PRISTUPOVY_KOD_PACIENT
	ON PRISTUPOVY_KOD (ID_PACIENTA);
CREATE INDEX IDX_OTP_KOD
	ON PRISTUPOVY_KOD (OTP_KOD, PLATNOST_DO);
CREATE INDEX IXFK_PRISTUPOVY_KOD_OTP_KOD
	ON PRISTUPOVY_KOD (OTP_KOD);
ALTER TABLE PRISTUPOVY_KOD
	ADD CONSTRAINT UQ_PRISTUPOVY_KOD_OTP_KOD UNIQUE (OTP_KOD);
CREATE INDEX IXFK_PRISTUPOVY_KOD_LEKARNICI
	ON PRISTUPOVY_KOD (ID_VYDAVAJICIHO_LEKARNIKA);
CREATE INDEX IXFK_PRISTUPOVY_KOD_LEKARI
	ON PRISTUPOVY_KOD (ID_PREDEPISUJICIHO_LEKARE);
CREATE INDEX IXFK_ZASTUP_PACIENT
	ON ZASTUP (ZASTUPOVANY_ID);
CREATE INDEX IXFK_ZASTUP_PACIENT_02
	ON ZASTUP (ZASTUPUJICI_ID);
ALTER TABLE ZASTUP
	ADD CONSTRAINT UQ_ZASTUP UNIQUE (ZASTUPOVANY_ID, ZASTUPUJICI_ID);
ALTER TABLE ZASTUP
	ADD CONSTRAINT check_zastup CHECK (zastupovany_id <> zastupujici_id);
CREATE INDEX IXFK_ZPRAVA_PACIENT
	ON ZPRAVA (ID_PACIENTA);
CREATE INDEX IXFK_ZPRAVA_LEKARNICI
	ON ZPRAVA (ID_VYDAVAJICIHO_LEKARNIKA);
CREATE INDEX IXFK_ZPRAVA_LEKARI
	ON ZPRAVA (ID_PREDEPISUJICIHO_LEKARE);
/* Create Primary Key Constraints */
ALTER TABLE LEKARI ADD CONSTRAINT PK_LEKARI 
	PRIMARY KEY (ID);


ALTER TABLE LEKARNICI ADD CONSTRAINT PK_LEKARNICI 
	PRIMARY KEY (ID);


ALTER TABLE NASTAVENI ADD CONSTRAINT PK_NASTAVENI 
	PRIMARY KEY (ID);


ALTER TABLE OTP_KOD ADD CONSTRAINT PK_OTP_KOD 
	PRIMARY KEY (ID);


ALTER TABLE PACIENT ADD CONSTRAINT PK_PACIENT 
	PRIMARY KEY (ID);


ALTER TABLE PREDPIS ADD CONSTRAINT PK_PREDPIS 
	PRIMARY KEY (ID);


ALTER TABLE PRISTUPOVY_KOD ADD CONSTRAINT PK_PRISTUPOVY_KOD 
	PRIMARY KEY (ID);


ALTER TABLE VYROBCI_SW ADD CONSTRAINT VYROBCI_SW_PK 
	PRIMARY KEY (ID);


ALTER TABLE ZASTUP ADD CONSTRAINT PK_Zastup 
	PRIMARY KEY (ID);


ALTER TABLE ZPRAVA ADD CONSTRAINT PK_ZPRAVA 
	PRIMARY KEY (ID);




/* Create Foreign Key Constraints */
ALTER TABLE KARTA ADD CONSTRAINT FK_KARTA_PACIENT 
	FOREIGN KEY (ID_PACIENTA) REFERENCES PACIENT (ID)
ON DELETE CASCADE;

ALTER TABLE LEKARI ADD CONSTRAINT FK_LEKARI_VYROBCI_SW 
	FOREIGN KEY (ID_VYROBCE_SW) REFERENCES VYROBCI_SW (ID)
ON DELETE SET NULL;

ALTER TABLE LEKARNICI ADD CONSTRAINT FK_LEKARNICI_VYROBCI_SW 
	FOREIGN KEY (ID_VYROBCE_SW) REFERENCES VYROBCI_SW (ID)
ON DELETE SET NULL;

ALTER TABLE NASTAVENI ADD CONSTRAINT FK_NASTAVENI_PACIENT 
	FOREIGN KEY (ID_PACIENTA) REFERENCES PACIENT (ID)
ON DELETE CASCADE;

ALTER TABLE PACIENT ADD CONSTRAINT FK_PACIENT_OTP_KOD_02 
	FOREIGN KEY (OTP_KOD_PROPRIHLASENI) REFERENCES OTP_KOD (ID)
ON DELETE SET NULL;

ALTER TABLE PACIENT ADD CONSTRAINT FK_PACIENT_OTP_KOD 
	FOREIGN KEY (OTP_KOD_PROZASTUPOVANI) REFERENCES OTP_KOD (ID)
ON DELETE SET NULL;

ALTER TABLE PREDPIS ADD CONSTRAINT FK_PREDPIS_PACIENT 
	FOREIGN KEY (ID_PACIENTA) REFERENCES PACIENT (ID)
ON DELETE CASCADE;

ALTER TABLE PREDPIS ADD CONSTRAINT FK_PREDPIS_LEKARNICI 
	FOREIGN KEY (ID_PREDEPISUJICIHO_LEKARNIKA) REFERENCES LEKARNICI (ID)
ON DELETE CASCADE;

ALTER TABLE PREDPIS ADD CONSTRAINT FK_PREDPIS_LEKARNICI_02 
	FOREIGN KEY (ID_VYDAVAJICIHO_LEKARNIKA) REFERENCES LEKARNICI (ID)
ON DELETE CASCADE;

ALTER TABLE PREDPIS ADD CONSTRAINT FK_PREDPIS_LEKARI 
	FOREIGN KEY (ID_PREDEPISUJICIHO_LEKARE) REFERENCES LEKARI (ID)
ON DELETE CASCADE;

ALTER TABLE PRISTUPOVY_KOD ADD CONSTRAINT FK_PRISTUPOVY_KOD_PACIENT 
	FOREIGN KEY (ID_PACIENTA) REFERENCES PACIENT (ID)
ON DELETE CASCADE;

ALTER TABLE PRISTUPOVY_KOD ADD CONSTRAINT FK_PRISTUPOVY_KOD_OTP_KOD 
	FOREIGN KEY (OTP_KOD) REFERENCES OTP_KOD (ID)
ON DELETE SET NULL;

ALTER TABLE PRISTUPOVY_KOD ADD CONSTRAINT FK_PRISTUPOVY_KOD_LEKARNICI 
	FOREIGN KEY (ID_VYDAVAJICIHO_LEKARNIKA) REFERENCES LEKARNICI (ID)
ON DELETE CASCADE;

ALTER TABLE PRISTUPOVY_KOD ADD CONSTRAINT FK_PRISTUPOVY_KOD_LEKARI 
	FOREIGN KEY (ID_PREDEPISUJICIHO_LEKARE) REFERENCES LEKARI (ID)
ON DELETE CASCADE;

ALTER TABLE ZASTUP ADD CONSTRAINT FK_ZASTUP_PACIENT 
	FOREIGN KEY (ZASTUPOVANY_ID) REFERENCES PACIENT (ID)
ON DELETE CASCADE;

ALTER TABLE ZASTUP ADD CONSTRAINT FK_ZASTUP_PACIENT_02 
	FOREIGN KEY (ZASTUPUJICI_ID) REFERENCES PACIENT (ID)
ON DELETE CASCADE;

ALTER TABLE ZPRAVA ADD CONSTRAINT FK_ZPRAVA_PACIENT 
	FOREIGN KEY (ID_PACIENTA) REFERENCES PACIENT (ID)
ON DELETE CASCADE;

ALTER TABLE ZPRAVA ADD CONSTRAINT FK_ZPRAVA_LEKARNICI 
	FOREIGN KEY (ID_VYDAVAJICIHO_LEKARNIKA) REFERENCES LEKARNICI (ID)
ON DELETE CASCADE;

ALTER TABLE ZPRAVA ADD CONSTRAINT FK_ZPRAVA_LEKARI 
	FOREIGN KEY (ID_PREDEPISUJICIHO_LEKARE) REFERENCES LEKARI (ID)
ON DELETE CASCADE;
